spring:
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate:
        dialect:
        format_sql: false
    show-sql: true
    defer-datasource-initialization: false

  datasource:
    url:

  liquibase:
    change-log: db/changelog-dev.yaml

  h2:
    console:
      enabled: true
      path:

server:
  port: 8081