spring:
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
    show-sql: true
    defer-datasource-initialization: false

  datasource:
    url: jdbc:h2:file:./eduquiz

  liquibase:
    change-log: db/changelog-test.yaml

  h2:
    console:
      enabled: true
      path: /eduquiz

server:
  port: 8080