spring:
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/eduquiz
    username: postgres
    password: password

  liquibase:
    change-log: db/changelog-prod.yaml
    contexts: prod